import { StyleSheet } from 'react-native';
import { lightTheme } from '../../theme';

export const createBotWizardStyles = StyleSheet.create({
  container: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 16,
    paddingBottom: 44,
  },
  headerSubtitle: {
    color: '#ffffff',
    fontSize: 14,
    textAlign: 'center',
    marginBottom: 8,
  },
  progressRow: {
    flexDirection: 'row',
    gap: 6,
    marginBottom: 22,
  },
  progressDot: {
    flex: 1,
    height: 6,
    borderRadius: 999,
    backgroundColor: lightTheme.colors.wave[400],
  },
  progressDotActive: {
    backgroundColor: '#ffffff',
  },
  card: {
    backgroundColor: lightTheme.colors.surface,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: lightTheme.colors.cardBorder,
    padding: 16,
    marginBottom: 12,
  },
  stepLabel: {
    fontSize: 12,
    textTransform: 'uppercase',
    letterSpacing: 0.6,
    color: lightTheme.colors.wave[500],
    fontWeight: '700',
  },
  stepTitle: {
    fontSize: 22,
    color: lightTheme.colors.wave[900],
    fontWeight: '700',
    marginTop: 4,
  },
  stepDescription: {
    color: lightTheme.colors.wave[600],
    fontSize: 14,
    marginTop: 6,
    marginBottom: 16,
    lineHeight: 20,
  },
  sectionLabel: {
    fontSize: 13,
    color: lightTheme.colors.wave[700],
    fontWeight: '700',
    marginBottom: 8,
  },
  input: {
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    borderRadius: 12,
    backgroundColor: '#fff',
    paddingHorizontal: 12,
    paddingVertical: 11,
    fontSize: 16,
    color: lightTheme.colors.wave[900],
    marginBottom: 12,
  },
  optionCard: {
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    backgroundColor: '#fff',
  },
  optionCardActive: {
    borderColor: lightTheme.colors.primary[700],
    backgroundColor: '#d9edff',
  },
  optionTitle: {
    color: lightTheme.colors.wave[900],
    fontSize: 15,
    fontWeight: '700',
  },
  optionDescription: {
    color: lightTheme.colors.wave[600],
    marginTop: 4,
    fontSize: 13,
  },
  recommendedTag: {
    alignSelf: 'flex-start',
    marginTop: 7,
    borderRadius: 999,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: lightTheme.colors.bullish[100],
  },
  recommendedTagText: {
    color: lightTheme.colors.bullish[700],
    fontSize: 11,
    fontWeight: '700',
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 10,
  },
  chip: {
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    borderRadius: 999,
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: '#fff',
  },
  chipActive: {
    borderColor: '#0b5ea8',
    backgroundColor: '#0b5ea8',
  },
  chipText: {
    color: lightTheme.colors.wave[800],
    fontSize: 13,
    fontWeight: '600',
  },
  chipTextActive: {
    color: '#ffffff',
    fontWeight: '700',
  },
  row: {
    flexDirection: 'row',
    gap: 10,
  },
  half: {
    flex: 1,
  },
  helperText: {
    marginTop: -2,
    marginBottom: 12,
    color: lightTheme.colors.wave[500],
    fontSize: 12,
  },
  instructionBox: {
    borderWidth: 1,
    borderColor: lightTheme.colors.primary[200],
    backgroundColor: lightTheme.colors.primary[50],
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  instructionTitle: {
    color: lightTheme.colors.primary[800],
    fontWeight: '700',
    fontSize: 14,
    marginBottom: 8,
  },
  instructionStep: {
    color: lightTheme.colors.wave[700],
    fontSize: 13,
    lineHeight: 19,
    marginBottom: 6,
  },
  inlineCode: {
    fontFamily: 'monospace',
    color: lightTheme.colors.primary[800],
  },
  switchRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    backgroundColor: '#fff',
  },
  switchTitle: {
    color: lightTheme.colors.wave[900],
    fontWeight: '700',
    fontSize: 14,
  },
  switchSubtitle: {
    color: lightTheme.colors.wave[500],
    marginTop: 2,
    fontSize: 12,
  },
  switchCopy: {
    flex: 1,
    paddingRight: 12,
  },
  assetCard: {
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[250],
    borderRadius: 12,
    backgroundColor: '#fff',
    padding: 10,
    marginBottom: 8,
  },
  assetCardActive: {
    borderColor: lightTheme.colors.primary[700],
    backgroundColor: lightTheme.colors.primary[50],
  },
  assetCardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  assetSymbol: {
    color: lightTheme.colors.wave[900],
    fontWeight: '700',
    fontSize: 14,
  },
  assetCustodian: {
    color: lightTheme.colors.wave[600],
    fontSize: 11,
    fontWeight: '600',
  },
  assetName: {
    color: lightTheme.colors.wave[700],
    fontSize: 12,
    marginTop: 4,
  },
  assetAddress: {
    color: lightTheme.colors.wave[500],
    fontSize: 10,
    marginTop: 6,
  },
  boatCarousel: {
    paddingBottom: 6,
  },
  boatModeVisual: {
    marginTop: 6,
    marginBottom: 12,
  },
  boatSlide: {
    alignItems: 'center',
    justifyContent: 'center',
  },
  boatImage: {
    width: '96%',
    height: 150,
  },
  captainCarousel: {
    paddingBottom: 4,
  },
  captainModeVisual: {
    marginBottom: 4,
  },
  captainSlide: {
    paddingHorizontal: 4,
  },
  captainImageFrame: {
    width: '100%',
    height: 290,
    borderRadius: 10,
    marginBottom: 10,
    overflow: 'hidden',
  },
  captainImage: {
    width: '100%',
    height: 340,
    transform: [{ translateY: 18 }],
  },
  captainName: {
    color: lightTheme.colors.wave[900],
    fontSize: 16,
    fontWeight: '700',
  },
  captainDescription: {
    color: lightTheme.colors.wave[600],
    fontSize: 13,
    marginTop: 6,
    lineHeight: 18,
  },
  factorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  factorBlock: {
    marginBottom: 10,
  },
  factorSelectButton: {
    flex: 1,
    minHeight: 42,
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    borderRadius: 10,
    backgroundColor: '#fff',
    paddingHorizontal: 10,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  factorSelectText: {
    flex: 1,
    color: lightTheme.colors.wave[800],
    fontSize: 13,
    fontWeight: '600',
    paddingRight: 8,
  },
  factorSelectChevron: {
    color: lightTheme.colors.wave[500],
    fontSize: 11,
    fontWeight: '700',
  },
  factorWeightInput: {
    width: 86,
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    borderRadius: 10,
    backgroundColor: '#fff',
    color: lightTheme.colors.wave[900],
    paddingVertical: 8,
    paddingHorizontal: 10,
    textAlign: 'right',
    fontSize: 13,
    fontWeight: '600',
  },
  factorRemoveButton: {
    minHeight: 42,
    borderWidth: 1,
    borderColor: lightTheme.colors.lobster[200],
    borderRadius: 10,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: lightTheme.colors.lobster[50],
  },
  factorRemoveText: {
    color: lightTheme.colors.lobster[700],
    fontSize: 12,
    fontWeight: '700',
  },
  factorDropdownMenu: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[250],
    borderRadius: 10,
    backgroundColor: '#fff',
    overflow: 'hidden',
  },
  factorDropdownItem: {
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: lightTheme.colors.wave[150],
  },
  factorDropdownItemDisabled: {
    backgroundColor: lightTheme.colors.wave[100],
  },
  factorDropdownText: {
    color: lightTheme.colors.wave[800],
    fontSize: 13,
    fontWeight: '600',
  },
  factorDropdownTextDisabled: {
    color: lightTheme.colors.wave[400],
  },
  formulaPreview: {
    marginTop: 12,
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: lightTheme.colors.wave[100],
    color: lightTheme.colors.wave[800],
    fontSize: 13,
    fontWeight: '700',
  },
  coefficientWarning: {
    marginTop: 6,
    marginBottom: 12,
    color: lightTheme.colors.lobster[700],
    fontSize: 12,
    fontWeight: '700',
  },
  addFactorButton: {
    marginTop: 6,
    borderWidth: 1,
    borderColor: lightTheme.colors.primary[400],
    borderRadius: 10,
    backgroundColor: lightTheme.colors.primary[100],
    paddingVertical: 10,
    alignItems: 'center',
  },
  addFactorButtonDisabled: {
    borderColor: lightTheme.colors.wave[250],
    backgroundColor: lightTheme.colors.wave[100],
  },
  addFactorButtonText: {
    color: lightTheme.colors.primary[700],
    fontSize: 13,
    fontWeight: '700',
  },
  inlineError: {
    color: lightTheme.colors.lobster[600],
    fontWeight: '600',
    marginBottom: 10,
  },
  availableText: {
    color: lightTheme.colors.bullish[700],
    fontWeight: '700',
    marginBottom: 10,
    fontSize: 12,
  },
  nameUnavailableRow: {
    marginBottom: 10,
  },
  useSuggestionText: {
    color: lightTheme.colors.primary[700],
    fontWeight: '700',
    fontSize: 12,
  },
  summaryRow: {
    marginBottom: 10,
    borderBottomWidth: 1,
    borderBottomColor: lightTheme.colors.wave[200],
    paddingBottom: 8,
  },
  summaryLabel: {
    fontSize: 12,
    color: lightTheme.colors.wave[500],
    textTransform: 'uppercase',
    letterSpacing: 0.4,
  },
  summaryValue: {
    color: lightTheme.colors.wave[900],
    fontSize: 15,
    fontWeight: '600',
    marginTop: 2,
  },
  footerRow: {
    flexDirection: 'row',
    gap: 10,
    marginTop: 4,
  },
  backButton: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: lightTheme.colors.wave[300],
    backgroundColor: lightTheme.colors.wave[100],
    paddingVertical: 13,
    alignItems: 'center',
  },
  backButtonText: {
    color: lightTheme.colors.wave[700],
    fontWeight: '700',
    fontSize: 15,
  },
  nextButton: {
    flex: 1.5,
    borderRadius: 14,
    backgroundColor: '#0b5ea8',
    paddingVertical: 13,
    alignItems: 'center',
  },
  nextButtonDisabled: {
    backgroundColor: lightTheme.colors.wave[300],
  },
  nextButtonText: {
    color: '#fff',
    fontWeight: '700',
    fontSize: 15,
  },
});
