import { StyleSheet } from 'react-native';
import { lightTheme } from '../../theme';

export const authScreenStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#032746',
  },
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(2, 21, 40, 0.36)',
  },
  keyboardContainer: {
    flex: 1,
  },
  scrollContent: {
    flexGrow: 1,
    justifyContent: 'flex-start',
    paddingHorizontal: 18,
  },
  loadingContainer: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#e9f5ff',
    paddingHorizontal: 24,
  },
  loadingAvatar: {
    width: 84,
    height: 84,
    borderRadius: 42,
    marginBottom: 14,
  },
  loadingText: {
    fontSize: 16,
    color: '#12314d',
    marginBottom: 8,
  },
  loadingSpinner: {
    marginTop: 6,
  },
  heroSection: {
    paddingTop: 4,
    minHeight: 86,
    justifyContent: 'flex-start',
  },
  brandRow: {
    position: 'relative',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 56,
  },
  brandMark: {
    position: 'absolute',
    left: 0,
    width: 50,
    height: 50,
    borderRadius: 25,
    borderWidth: 2,
    borderColor: 'rgba(255,255,255,0.75)',
  },
  brandTitle: {
    fontSize: 34,
    lineHeight: 36,
    fontWeight: 'normal',
    color: '#f2f9ff',
    fontFamily: 'BNRumble',
    textAlign: 'center',
  },
  sheet: {
    backgroundColor: 'rgba(245, 252, 255, 0.97)',
    borderTopLeftRadius: 28,
    borderTopRightRadius: 28,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    paddingHorizontal: 18,
    paddingTop: 16,
    paddingBottom: 28,
    shadowColor: '#001021',
    shadowOffset: { width: 0, height: -4 },
    shadowOpacity: 0.16,
    shadowRadius: 10,
    elevation: 9,
    marginTop: 8,
  },
  modeRow: {
    flexDirection: 'row',
    backgroundColor: '#dfefff',
    borderRadius: 999,
    padding: 4,
    marginBottom: 14,
  },
  modePill: {
    flex: 1,
    borderRadius: 999,
    alignItems: 'center',
    paddingVertical: 9,
  },
  modePillActive: {
    backgroundColor: '#ffffff',
    shadowColor: '#103554',
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  modePillText: {
    color: '#456486',
    fontWeight: '600',
    fontSize: 14,
  },
  modePillTextActive: {
    color: '#0f2f4a',
  },
  fieldGroup: {
    marginBottom: 10,
  },
  fieldLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#35536f',
    marginBottom: 6,
  },
  input: {
    borderWidth: 1,
    borderColor: '#9ec0db',
    borderRadius: 12,
    backgroundColor: '#ffffff',
    paddingHorizontal: 12,
    paddingRight: 58,
    paddingVertical: 11,
    fontSize: 16,
    color: '#102c44',
  },
  passwordToggle: {
    position: 'absolute',
    right: 12,
    top: 33,
    paddingVertical: 4,
    paddingHorizontal: 4,
  },
  passwordToggleText: {
    color: '#0c64b5',
    fontSize: 12,
    fontWeight: '600',
  },
  fieldError: {
    color: '#cc1f1f',
    fontSize: 12,
    marginTop: 5,
  },
  primaryButton: {
    marginTop: 6,
    borderRadius: 14,
    backgroundColor: '#0c64b5',
    alignItems: 'center',
    paddingVertical: 13,
  },
  primaryButtonDisabled: {
    backgroundColor: '#83add2',
  },
  primaryButtonText: {
    color: '#ffffff',
    fontSize: 17,
    fontWeight: '700',
  },
  inlineLink: {
    alignSelf: 'center',
    marginTop: 10,
    paddingVertical: 4,
  },
  inlineLinkText: {
    fontSize: 13,
    color: '#0c64b5',
    fontWeight: '600',
  },
  orRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 14,
    marginBottom: 14,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#c3d7e8',
  },
  orText: {
    marginHorizontal: 10,
    color: '#577797',
    fontSize: 13,
  },
  googleButton: {
    borderRadius: 14,
    overflow: 'hidden',
  },
  proofRow: {
    marginTop: 18,
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  proofItem: {
    color: '#3b5f82',
    fontSize: 12,
    fontWeight: '600',
  },
  proofDot: {
    marginHorizontal: 8,
    color: '#6f8ea8',
    fontSize: 12,
  },
  reassurance: {
    marginTop: 16,
    color: '#506b84',
    textAlign: 'center',
    fontSize: 12,
    lineHeight: 17,
    paddingHorizontal: 8,
  },
  metaLinksRow: {
    marginTop: 16,
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
  },
  metaLink: {
    color: '#4f7091',
    fontSize: 12,
    fontWeight: '600',
    paddingHorizontal: 3,
  },
  metaDivider: {
    color: '#8aa6bf',
    marginHorizontal: 4,
  },
});
